apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- configmap.yaml
- service.yaml
- gateway.yaml
- virtual-service.yaml
- config-deploy.yaml
images:
- name: configmap-app
  newName: configmap-app
  newTag: latest